### ISSUE TITLE
Remote introspection fails  for Webpack-bundles "TypeError: e.fetch is not a function"

### ISSUE THREAD

**Issue by ghost** [schibsted/node-token-introspection#29] opened 2022-04-28 07:37 UTC
Greetings!

If bundled with webpack the remote introspection failed with following error:

```
Remote introspection request failed
    at /<path-to-file>/main.js:2:3374174
    at /<path-to-file>/main.js:2:3371803
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async c.validate (/<path-to-file>/main.js:2:3386340)
```

After a moment of debugging we found out that the real error underneath was a `TypeError: e.fetch is not a function` in the bundle

A hoffix was to add `.default` to node-fetch import in index.js:26.

```js
options.fetch = require('node-fetch').default;
```

**Comment by joawan** [comment] 2022-04-28 07:45
What version of node-fetch are you running? v3.x?

**Comment by ghost** [comment] 2022-04-28 08:02
We checked 1.x, 2.x and 3.x versions. Non of them worked. :(

**Comment by joawan** [comment] 2022-04-28 08:19
Version 1 and 2 should work, unless you are transpiling them to ES modules.
Version 3 of node-fetch is ESM only, which requires either import or `.default`. 

I'll look into updating fetch to v3.
This is then a duplicate of #26 but I'll keep it open.

Thanks for reporting!

**Comment by joawan** [comment] 2023-01-10 22:30
Sorry, this took a while....

PR #34 should fix the issue.
I confused it a bit with supporting node-fetch 3x and esm, but will need to look into that separately.

**Comment by joawan** [comment] 2023-01-10 23:00
Well, @ghost won't answer. Closing this.

**Closed as completed by joawan** 2023-01-10 23:00 UTC
